export interface Theme {
  id: string;
  name: string;
  description: string;
  type: 'Standard' | 'Premium' | 'Legendary' | 'Mythic'; // [NEW] Mythic Tier
  cost: number;
  currency: 'stardust' | 'cometShards';
  
  // Shop Visuals
  previewColor: string; 

  // App Visuals (CSS/Tailwind)
  background: string;   
  gridBorder: string;
  gridColor: string; 
  numColor: string;     
  
  // Animation Visuals (Hex)
  accentHex: string;    

  // Visual Safety Flags
  requiresDimming?: boolean; // Dark overlay for light themes
  isDynamic?: boolean;       // [NEW] Triggers CSS animation for fluid backgrounds
}

export const SHOP_THEMES: Theme[] = [
  // --- TIER 1: STANDARD (Stardust) ---
  {
    id: 'midnight',
    name: 'Midnight Void',
    description: 'The standard protocol. Clean and efficient.',
    type: 'Standard',
    cost: 0,
    currency: 'stardust',
    previewColor: '#0F172A',
    background: 'radial-gradient(circle at center, #1e293b 0%, #0F172A 100%)',
    gridBorder: 'border-white/20',
    gridColor: 'rgba(255, 255, 255, 0.1)',
    numColor: 'text-neon-cyan',
    accentHex: '#22d3ee', 
  },
  {
    id: 'twilight',
    name: 'Twilight',
    description: 'Soft purples for deep focus.',
    type: 'Standard',
    cost: 250,
    currency: 'stardust',
    previewColor: '#4c1d95',
    background: 'linear-gradient(to bottom, #2e1065, #0f172a)',
    gridBorder: 'border-violet-500/30',
    gridColor: 'rgba(139, 92, 246, 0.15)',
    numColor: 'text-violet-300',
    accentHex: '#a78bfa',
  },
  {
    id: 'matrix',
    name: 'Construct',
    description: 'Raw code visibility. See the logic.',
    type: 'Standard',
    cost: 500,
    currency: 'stardust',
    previewColor: '#10b981',
    background: 'radial-gradient(circle at center, rgba(16, 185, 129, 0.15) 0%, #022c22 80%, #000000 100%)',
    gridBorder: 'border-emerald-500/30',
    gridColor: 'rgba(16, 185, 129, 0.2)',
    numColor: 'text-emerald-400',
    accentHex: '#34d399', 
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Architectural precision. Royal blue aesthetics.',
    type: 'Standard',
    cost: 750,
    currency: 'stardust',
    previewColor: '#1e40af',
    background: 'linear-gradient(135deg, #172554 0%, #1e3a8a 100%)',
    gridBorder: 'border-blue-400/40',
    gridColor: 'rgba(96, 165, 250, 0.2)',
    numColor: 'text-blue-200',
    accentHex: '#60a5fa',
  },
  {
    id: 'sunset',
    name: 'Horizon',
    description: 'Focus in the warmth of a dying star.',
    type: 'Standard',
    cost: 1000,
    currency: 'stardust',
    previewColor: '#f59e0b',
    background: 'radial-gradient(circle at center, rgba(245, 158, 11, 0.15) 0%, #451a03 80%, #000000 100%)',
    gridBorder: 'border-orange-500/30',
    gridColor: 'rgba(249, 115, 22, 0.2)',
    numColor: 'text-orange-400',
    accentHex: '#fb923c', 
  },
  {
    id: 'sepia',
    name: 'Archive',
    description: 'Ancient data logs. Retro warmth.',
    type: 'Standard',
    cost: 1250,
    currency: 'stardust',
    previewColor: '#78350f',
    background: '#292524',
    gridBorder: 'border-stone-500/40',
    gridColor: 'rgba(214, 211, 209, 0.15)',
    numColor: 'text-amber-100',
    accentHex: '#f59e0b',
  },
  {
    id: 'glacier',
    name: 'Permafrost',
    description: 'Cold logic. High contrast visibility.',
    type: 'Standard',
    cost: 1500,
    currency: 'stardust',
    previewColor: '#e0f2fe',
    background: 'radial-gradient(circle at center, #0c4a6e 0%, #082f49 100%)',
    gridBorder: 'border-sky-300/30',
    gridColor: 'rgba(125, 211, 252, 0.2)',
    numColor: 'text-sky-200',
    accentHex: '#bae6fd', 
  },
  {
    id: 'verdant',
    name: 'Overgrowth',
    description: 'Nature reclaiming the machine.',
    type: 'Standard',
    cost: 2000,
    currency: 'stardust',
    previewColor: '#4ade80',
    background: 'radial-gradient(circle at center, rgba(20, 83, 45, 0.4) 0%, #052e16 100%)',
    gridBorder: 'border-green-500/30',
    gridColor: 'rgba(74, 222, 128, 0.2)',
    numColor: 'text-green-400',
    accentHex: '#4ade80',
  },
  {
    id: 'abyss',
    name: 'The Abyss',
    description: 'Deep pressure. Crushing depths.',
    type: 'Standard',
    cost: 2500,
    currency: 'stardust',
    previewColor: '#06b6d4',
    background: 'radial-gradient(circle at bottom, #155e75 0%, #083344 100%)',
    gridBorder: 'border-cyan-700/50',
    gridColor: 'rgba(6, 182, 212, 0.2)',
    numColor: 'text-cyan-300',
    accentHex: '#22d3ee',
  },

  // --- TIER 2: PREMIUM (Comet Shards) ---
  {
    id: 'nebula',
    name: 'Nebula',
    description: 'Forged from the heart of a galaxy.',
    type: 'Premium',
    cost: 5,
    currency: 'cometShards',
    previewColor: '#8b5cf6',
    background: 'radial-gradient(circle at center, rgba(139, 92, 246, 0.2) 0%, #2e1065 70%, #000000 100%)',
    gridBorder: 'border-purple-500/40',
    gridColor: 'rgba(168, 85, 247, 0.2)',
    numColor: 'text-purple-400',
    accentHex: '#c084fc', 
  },
  {
    id: 'dracula',
    name: 'Vampire',
    description: 'Gothic elegance. Dark charcoal and pink.',
    type: 'Premium',
    cost: 5,
    currency: 'cometShards',
    previewColor: '#f472b6',
    background: '#282a36',
    gridBorder: 'border-pink-500/40',
    gridColor: 'rgba(244, 114, 182, 0.15)',
    numColor: 'text-pink-300',
    accentHex: '#ff79c6',
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    description: 'Neon sunsets and digital dreams.',
    type: 'Premium',
    cost: 6,
    currency: 'cometShards',
    previewColor: '#d946ef',
    background: 'linear-gradient(to bottom, #2e1065 0%, #4a044e 100%)',
    gridBorder: 'border-fuchsia-500/40',
    gridColor: 'rgba(232, 121, 249, 0.25)',
    numColor: 'text-fuchsia-400',
    accentHex: '#e879f9',
  },
  {
    id: 'sakura',
    name: 'Blossom',
    description: 'Peaceful pink hues. Requires focus.',
    type: 'Premium',
    cost: 8,
    currency: 'cometShards',
    previewColor: '#f472b6',
    background: 'radial-gradient(circle at center, rgba(244, 114, 182, 0.15) 0%, #500724 80%, #000000 100%)',
    gridBorder: 'border-pink-400/30',
    gridColor: 'rgba(244, 114, 182, 0.2)',
    numColor: 'text-pink-300',
    accentHex: '#f9a8d4', 
  },
  {
    id: 'cyber',
    name: 'Edgerunner',
    description: 'High-tech yellow against deep blue.',
    type: 'Premium',
    cost: 10,
    currency: 'cometShards',
    previewColor: '#facc15',
    background: 'linear-gradient(to bottom right, #172554, #000000)',
    gridBorder: 'border-yellow-400/40',
    gridColor: 'rgba(250, 204, 21, 0.2)',
    numColor: 'text-yellow-400',
    accentHex: '#facc15', 
  },
  {
    id: 'midas',
    name: 'Midas Touch',
    description: 'Luxury gold for the high rollers.',
    type: 'Premium',
    cost: 12,
    currency: 'cometShards',
    previewColor: '#fbbf24',
    background: 'radial-gradient(circle at center, rgba(180, 83, 9, 0.2) 0%, #451a03 100%)',
    gridBorder: 'border-amber-400/40',
    gridColor: 'rgba(251, 191, 36, 0.25)',
    numColor: 'text-amber-300',
    accentHex: '#fcd34d',
  },

  // --- TIER 3: LEGENDARY (Comet Shards) ---
  {
    id: 'crimson',
    name: 'Singularity',
    description: 'The event horizon. Aggressive and bold.',
    type: 'Legendary',
    cost: 15,
    currency: 'cometShards',
    previewColor: '#ef4444',
    background: 'radial-gradient(circle at center, rgba(153, 27, 27, 0.4) 0%, #000000 90%)',
    gridBorder: 'border-red-600/50',
    gridColor: 'rgba(220, 38, 38, 0.3)',
    numColor: 'text-red-500',
    accentHex: '#ef4444', 
  },
  {
    id: 'noir',
    name: 'Noir',
    description: 'Total desaturation. Pure focus.',
    type: 'Legendary',
    cost: 20,
    currency: 'cometShards',
    previewColor: '#ffffff',
    background: '#000000',
    gridBorder: 'border-white/40',
    gridColor: 'rgba(255, 255, 255, 0.15)',
    numColor: 'text-white',
    accentHex: '#ffffff', 
  },
  {
    id: 'void',
    name: 'True Void',
    description: 'The absence of light. Minimalist perfection.',
    type: 'Legendary',
    cost: 25,
    currency: 'cometShards',
    previewColor: '#171717',
    background: 'radial-gradient(circle at bottom, #262626 0%, #000000 100%)',
    gridBorder: 'border-neutral-700',
    gridColor: 'rgba(64, 64, 64, 0.3)',
    numColor: 'text-neutral-200',
    accentHex: '#e5e5e5', 
  },
  {
    id: 'hyperion',
    name: 'Hyperion',
    description: 'Multiversal energy. Shifts across the spectrum.',
    type: 'Legendary',
    cost: 28,
    currency: 'cometShards',
    previewColor: '#8b5cf6',
    background: 'linear-gradient(45deg, #1e1b4b, #312e81, #4c1d95)',
    gridBorder: 'border-fuchsia-500/50',
    gridColor: 'rgba(216, 180, 254, 0.2)',
    numColor: 'text-fuchsia-300',
    accentHex: '#d8b4fe',
  },
  {
    id: 'lumina',
    name: 'Lumina',
    description: 'Blinding light. Dimmed for safety.',
    type: 'Legendary',
    cost: 30,
    currency: 'cometShards',
    previewColor: '#f8fafc',
    background: 'radial-gradient(circle at center, #e2e8f0 0%, #cbd5e1 100%)',
    gridBorder: 'border-slate-300',
    gridColor: 'rgba(255, 255, 255, 0.3)',
    numColor: 'text-white',
    accentHex: '#ffffff',
    requiresDimming: true,
  },

  // --- TIER 4: MYTHIC (The Dynamic Theme) ---
  {
    id: 'eternity',
    name: 'Eternity',
    description: 'A living paradox. The colors of the cosmos in flux.',
    type: 'Mythic',
    cost: 100, // The Ultimate Flex
    currency: 'cometShards',
    previewColor: '#ffffff',
    // We use a multi-color gradient that will be animated by CSS
    background: 'linear-gradient(270deg, #ff0080, #ff8c00, #40e0d0, #ff0080)',
    gridBorder: 'border-white/50',
    gridColor: 'rgba(255, 255, 255, 0.2)',
    numColor: 'text-white',
    accentHex: '#ffffff',
    requiresDimming: true, // It's bright/chaotic, so dim it slightly
    isDynamic: true, // [NEW] Triggers the 'animate-gradient-xy' class
  },
];

export const getThemeById = (id: string): Theme => {
  return SHOP_THEMES.find((t) => t.id === id) || SHOP_THEMES[0];
};