import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import dbConnect from "@/lib/db/connect";
import DailyScore from "@/lib/db/models/DailyScore";
import User from "@/lib/db/models/User";

// Force dynamic to ensure we don't cache the "Completed: false" state
export const dynamic = 'force-dynamic';

export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user?.email) {
      return NextResponse.json({ completed: false });
    }

    await dbConnect();
    
    // 1. Get User ID
    const user = await User.findOne({ email: session.user.email }).select("_id");
    if (!user) return NextResponse.json({ completed: false });

    // 2. Check for Today's Score (UTC)
    // This matches the date string format generated by the client and generator
    const today = new Date().toISOString().split('T')[0];
    
    // Efficiently check existence without fetching the whole document
    const exists = await DailyScore.exists({ userId: user._id, date: today });

    return NextResponse.json({ completed: !!exists });

  } catch (error) {
    console.error("Daily Status Check Error:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}